language: python
python:
    - '2.7'

services:
  - docker

env:
  global:
    - VERSION=1.4
    - REPO=synst/s3-dockup

script:
  - python build.py

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $REPO
