language: python
python:
    - '2.7'

services:
  - docker

env:
  global:
    - VERSION=1.3

script:
  - python build.py

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=$DOCKER_USER/docker-backup
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO .
  - docker tag $REPO $REPO:$TAG
  - docker tag $REPO $REPO:$VERSION
  - docker tag $REPO $REPO:$VERSION-travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
