language: python
python:
    - '2.7'

env:
  global:
    - VERSION=1.5
    - REPO=synst/s3-dockup

before_script:
  - echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin

script:
  - ./build.sh

after_script:
  - docker tag $REPO $REPO:latest
  - docker tag $REPO $REPO:$VERSION
  - docker tag $REPO $REPO:$VERSION.$TRAVIS_BUILD_NUMBER
  - echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
  - docker push $REPO
  - docker push $REPO:$VERSION
  - docker push $REPO:$VERSION.$TRAVIS_BUILD_NUMBER
