language: python
python:
    - '2.7'

services:
  - docker

env:
  global:
    - VERSION=1.4
    - REPO=synst/s3-dockup

before_script:
  - echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin

script:
  - python build.py

after_script:
  - echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
  - docker push $REPO
