version: "3"
services:
  dockup:
    image: synstd/s3-dockup:latest
    container_name: dockup
    hostname: dockup
    environment:
      - BACKUP_NAME=
      - S3_BUCKET_NAME=
      - TIMEZONE=Europe/Moscow
      - BACKUP_PATHS=/var/www/html
      - BACKUP_TAR_OPTION=--exclude=/var/www/html/cmd-* --exclude=/var/www/html/adminer.php --exclude=/var/www/html/sites/default/files/php --exclude=/var/www/html/sites/default/files/translations
      - DBFILE=
      - AWS_DEFAULT_REGION=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_BUCKET=
      - AWS_CLI_PARAMS=
      - DBDUMP=mysql
      - DBSKIP=--structure-tables-list=cache,cache_*,cachetags,field_deleted_*,flood,history,search_*,sessions,watchdog,webprofiler
      - DBHOST=localhost
      - DBNAME=
      - DBUSER=
      - DBPASS=
      - DBRESTORE=
      - MATTERMOST=
      - MATTERMOST_HOST=
      - MATTERMOST_HOOK=
      - TELEGA_TOKEN=
      - TELEGA_CHANNEL=
      - APP_KEY=
      - APP_TEMPLATE=s3backup
      - MESSAGE_CHANNEL=
      - MQTT_HOST=
      - MQTT_PORT=
      - MQTT_USER=
      - MQTT_PASS=
      - SERVER_NID=
    volumes:
      - "./console/console.php:/opt/console/console.php"
      - "./console/.env:/opt/console/.env"
