s3-dockup :
  image: synst/s3-dockup
  container_name: s3-dockup-example
  hostname: s3-dockup-example
  environment:
    - TZ=Europe/Moscow
    - BACKUP_NAME=bcp-d-000-dockup-example
    - BACKUP_PATHS=/var/www /var/lib/mysql
    - S3_BUCKET_NAME=
    - AWS_DEFAULT_REGION=
    - AWS_ACCESS_KEY_ID=
    - AWS_SECRET_ACCESS_KEY=
    - BACKUP_TAR_OPTION=
    - DBDUMP=true
    - DBDUMPENGINE=drush
    - DBSKIP=--structure-tables-list=cache,cache_*,cachetags,search_*,watchdog,history,sessions
    - DBHOST=
    - DBNAME=drupal
    - DBUSER=drupal
    - DBFILE=/var/www/html/.db.sql
    # $RESTORE=false
  volumes:
    - "/opt/sites/0-default/www-home:/var/www:rw"
    - "/opt/sites/0-default/db:/var/lib/mysql:ro"
    - "/opt/sites/0-default/run/mysqld:/var/run/mysqld:ro"
